sonar.projectKey=eltu_idx
sonar.organization=eltu
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/bin/**,**/mocks/**,docs/**,**/tui/init_progress_tui.go,**/tui/init_progress_runner.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
