// Code generated by MockGen. DO NOT EDIT.
// Source: ../../../ports/daemon_repository.go
//
// Generated by this command:
//
//	mockgen -source=../../../ports/daemon_repository.go -destination=mock_daemon_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "idx/internal/core/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDaemonRepository is a mock of DaemonRepository interface.
type MockDaemonRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDaemonRepositoryMockRecorder
	isgomock struct{}
}

// MockDaemonRepositoryMockRecorder is the mock recorder for MockDaemonRepository.
type MockDaemonRepositoryMockRecorder struct {
	mock *MockDaemonRepository
}

// NewMockDaemonRepository creates a new mock instance.
func NewMockDaemonRepository(ctrl *gomock.Controller) *MockDaemonRepository {
	mock := &MockDaemonRepository{ctrl: ctrl}
	mock.recorder = &MockDaemonRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaemonRepository) EXPECT() *MockDaemonRepositoryMockRecorder {
	return m.recorder
}

// ReadState mocks base method.
func (m *MockDaemonRepository) ReadState() (*domain.DaemonState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadState")
	ret0, _ := ret[0].(*domain.DaemonState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadState indicates an expected call of ReadState.
func (mr *MockDaemonRepositoryMockRecorder) ReadState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadState", reflect.TypeOf((*MockDaemonRepository)(nil).ReadState))
}

// SaveState mocks base method.
func (m *MockDaemonRepository) SaveState(state *domain.DaemonState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveState", state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveState indicates an expected call of SaveState.
func (mr *MockDaemonRepositoryMockRecorder) SaveState(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveState", reflect.TypeOf((*MockDaemonRepository)(nil).SaveState), state)
}

// UpdateProjectPID mocks base method.
func (m *MockDaemonRepository) UpdateProjectPID(projectPath string, pid int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProjectPID", projectPath, pid)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProjectPID indicates an expected call of UpdateProjectPID.
func (mr *MockDaemonRepositoryMockRecorder) UpdateProjectPID(projectPath, pid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProjectPID", reflect.TypeOf((*MockDaemonRepository)(nil).UpdateProjectPID), projectPath, pid)
}
