// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/process_spawner.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/process_spawner.go -destination=internal/core/services/daemon/mocks/mock_process_spawner.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProcessSpawner is a mock of ProcessSpawner interface.
type MockProcessSpawner struct {
	ctrl     *gomock.Controller
	recorder *MockProcessSpawnerMockRecorder
	isgomock struct{}
}

// MockProcessSpawnerMockRecorder is the mock recorder for MockProcessSpawner.
type MockProcessSpawnerMockRecorder struct {
	mock *MockProcessSpawner
}

// NewMockProcessSpawner creates a new mock instance.
func NewMockProcessSpawner(ctrl *gomock.Controller) *MockProcessSpawner {
	mock := &MockProcessSpawner{ctrl: ctrl}
	mock.recorder = &MockProcessSpawnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessSpawner) EXPECT() *MockProcessSpawnerMockRecorder {
	return m.recorder
}

// SpawnWatchProcess mocks base method.
func (m *MockProcessSpawner) SpawnWatchProcess(projectPath string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpawnWatchProcess", projectPath)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpawnWatchProcess indicates an expected call of SpawnWatchProcess.
func (mr *MockProcessSpawnerMockRecorder) SpawnWatchProcess(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpawnWatchProcess", reflect.TypeOf((*MockProcessSpawner)(nil).SpawnWatchProcess), projectPath)
}
