// Code generated by MockGen. DO NOT EDIT.
// Source: idx/internal/features/daemon (interfaces: StateRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/features/daemon/mocks/mock_state_repository.go -package=mocks idx/internal/features/daemon StateRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	daemon "idx/internal/features/daemon"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStateRepository is a mock of StateRepository interface.
type MockStateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStateRepositoryMockRecorder
	isgomock struct{}
}

// MockStateRepositoryMockRecorder is the mock recorder for MockStateRepository.
type MockStateRepositoryMockRecorder struct {
	mock *MockStateRepository
}

// NewMockStateRepository creates a new mock instance.
func NewMockStateRepository(ctrl *gomock.Controller) *MockStateRepository {
	mock := &MockStateRepository{ctrl: ctrl}
	mock.recorder = &MockStateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateRepository) EXPECT() *MockStateRepositoryMockRecorder {
	return m.recorder
}

// ReadState mocks base method.
func (m *MockStateRepository) ReadState(projectPath string) (*daemon.ServerState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadState", projectPath)
	ret0, _ := ret[0].(*daemon.ServerState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadState indicates an expected call of ReadState.
func (mr *MockStateRepositoryMockRecorder) ReadState(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadState", reflect.TypeOf((*MockStateRepository)(nil).ReadState), projectPath)
}

// RemoveState mocks base method.
func (m *MockStateRepository) RemoveState(projectPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveState", projectPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveState indicates an expected call of RemoveState.
func (mr *MockStateRepositoryMockRecorder) RemoveState(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveState", reflect.TypeOf((*MockStateRepository)(nil).RemoveState), projectPath)
}

// SaveState mocks base method.
func (m *MockStateRepository) SaveState(projectPath string, state *daemon.ServerState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveState", projectPath, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveState indicates an expected call of SaveState.
func (mr *MockStateRepositoryMockRecorder) SaveState(projectPath, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveState", reflect.TypeOf((*MockStateRepository)(nil).SaveState), projectPath, state)
}
