// Code generated by MockGen. DO NOT EDIT.
// Source: idx/internal/features/indexing (interfaces: PathRunner)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInitPathRunner is a mock of PathRunner interface.
type MockInitPathRunner struct {
	ctrl     *gomock.Controller
	recorder *MockInitPathRunnerMockRecorder
	isgomock struct{}
}

// MockInitPathRunnerMockRecorder is the mock recorder for MockInitPathRunner.
type MockInitPathRunnerMockRecorder struct {
	mock *MockInitPathRunner
}

// NewMockInitPathRunner creates a new mock instance.
func NewMockInitPathRunner(ctrl *gomock.Controller) *MockInitPathRunner {
	mock := &MockInitPathRunner{ctrl: ctrl}
	mock.recorder = &MockInitPathRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInitPathRunner) EXPECT() *MockInitPathRunnerMockRecorder {
	return m.recorder
}

// RunFromPath mocks base method.
func (m *MockInitPathRunner) RunFromPath(projectPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunFromPath", projectPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunFromPath indicates an expected call of RunFromPath.
func (mr *MockInitPathRunnerMockRecorder) RunFromPath(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunFromPath", reflect.TypeOf((*MockInitPathRunner)(nil).RunFromPath), projectPath)
}
