// Code generated by MockGen. DO NOT EDIT.
// Source: idx/internal/features/indexing (interfaces: CommandInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockInitCommandInterface is a mock of CommandInterface interface.
type MockInitCommandInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInitCommandInterfaceMockRecorder
	isgomock struct{}
}

// MockInitCommandInterfaceMockRecorder is the mock recorder for MockInitCommandInterface.
type MockInitCommandInterfaceMockRecorder struct {
	mock *MockInitCommandInterface
}

// NewMockInitCommandInterface creates a new mock instance.
func NewMockInitCommandInterface(ctrl *gomock.Controller) *MockInitCommandInterface {
	mock := &MockInitCommandInterface{ctrl: ctrl}
	mock.recorder = &MockInitCommandInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInitCommandInterface) EXPECT() *MockInitCommandInterfaceMockRecorder {
	return m.recorder
}

// RunFromPath mocks base method.
func (m *MockInitCommandInterface) RunFromPath(projectPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunFromPath", projectPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunFromPath indicates an expected call of RunFromPath.
func (mr *MockInitCommandInterfaceMockRecorder) RunFromPath(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunFromPath", reflect.TypeOf((*MockInitCommandInterface)(nil).RunFromPath), projectPath)
}
