// Code generated by MockGen. DO NOT EDIT.
// Source: idx/internal/shared/filesystem (interfaces: ProjectTree)

// Package mocks is a generated GoMock package.
package mocks

import (
	filesystem "idx/internal/shared/filesystem"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectTree is a mock of ProjectTree interface.
type MockProjectTree struct {
	ctrl     *gomock.Controller
	recorder *MockProjectTreeMockRecorder
	isgomock struct{}
}

// MockProjectTreeMockRecorder is the mock recorder for MockProjectTree.
type MockProjectTreeMockRecorder struct {
	mock *MockProjectTree
}

// NewMockProjectTree creates a new mock instance.
func NewMockProjectTree(ctrl *gomock.Controller) *MockProjectTree {
	mock := &MockProjectTree{ctrl: ctrl}
	mock.recorder = &MockProjectTreeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectTree) EXPECT() *MockProjectTreeMockRecorder {
	return m.recorder
}

// CurrentDir mocks base method.
func (m *MockProjectTree) CurrentDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentDir indicates an expected call of CurrentDir.
func (mr *MockProjectTreeMockRecorder) CurrentDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentDir", reflect.TypeOf((*MockProjectTree)(nil).CurrentDir))
}

// Exists mocks base method.
func (m *MockProjectTree) Exists(path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockProjectTreeMockRecorder) Exists(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockProjectTree)(nil).Exists), path)
}

// FindGitRoot mocks base method.
func (m *MockProjectTree) FindGitRoot(startDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindGitRoot", startDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindGitRoot indicates an expected call of FindGitRoot.
func (mr *MockProjectTreeMockRecorder) FindGitRoot(startDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindGitRoot", reflect.TypeOf((*MockProjectTree)(nil).FindGitRoot), startDir)
}

// ReadDir mocks base method.
func (m *MockProjectTree) ReadDir(path string) ([]filesystem.DirectoryEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", path)
	ret0, _ := ret[0].([]filesystem.DirectoryEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockProjectTreeMockRecorder) ReadDir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockProjectTree)(nil).ReadDir), path)
}

// RemoveAll mocks base method.
func (m *MockProjectTree) RemoveAll(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockProjectTreeMockRecorder) RemoveAll(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockProjectTree)(nil).RemoveAll), path)
}

// WriteFile mocks base method.
func (m *MockProjectTree) WriteFile(path string, content []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", path, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockProjectTreeMockRecorder) WriteFile(path, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockProjectTree)(nil).WriteFile), path, content)
}
