// Code generated by MockGen. DO NOT EDIT.
// Source: idx/internal/features/daemon (interfaces: ServerSpawner)
//
// Generated by this command:
//
//	mockgen -destination=internal/features/daemon/mocks/mock_server_spawner.go -package=mocks idx/internal/features/daemon ServerSpawner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServerSpawner is a mock of ServerSpawner interface.
type MockServerSpawner struct {
	ctrl     *gomock.Controller
	recorder *MockServerSpawnerMockRecorder
	isgomock struct{}
}

// MockServerSpawnerMockRecorder is the mock recorder for MockServerSpawner.
type MockServerSpawnerMockRecorder struct {
	mock *MockServerSpawner
}

// NewMockServerSpawner creates a new mock instance.
func NewMockServerSpawner(ctrl *gomock.Controller) *MockServerSpawner {
	mock := &MockServerSpawner{ctrl: ctrl}
	mock.recorder = &MockServerSpawnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerSpawner) EXPECT() *MockServerSpawnerMockRecorder {
	return m.recorder
}

// SpawnServerProcess mocks base method.
func (m *MockServerSpawner) SpawnServerProcess(projectPath string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpawnServerProcess", projectPath)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpawnServerProcess indicates an expected call of SpawnServerProcess.
func (mr *MockServerSpawnerMockRecorder) SpawnServerProcess(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpawnServerProcess", reflect.TypeOf((*MockServerSpawner)(nil).SpawnServerProcess), projectPath)
}
