// Code generated by MockGen. DO NOT EDIT.
// Source: idx/internal/shared/output (interfaces: Writer)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTextOutput is a mock of Writer interface.
type MockTextOutput struct {
	ctrl     *gomock.Controller
	recorder *MockTextOutputMockRecorder
	isgomock struct{}
}

// MockTextOutputMockRecorder is the mock recorder for MockTextOutput.
type MockTextOutputMockRecorder struct {
	mock *MockTextOutput
}

// NewMockTextOutput creates a new mock instance.
func NewMockTextOutput(ctrl *gomock.Controller) *MockTextOutput {
	mock := &MockTextOutput{ctrl: ctrl}
	mock.recorder = &MockTextOutputMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextOutput) EXPECT() *MockTextOutputMockRecorder {
	return m.recorder
}

// WriteLine mocks base method.
func (m *MockTextOutput) WriteLine(text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteLine", text)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteLine indicates an expected call of WriteLine.
func (mr *MockTextOutputMockRecorder) WriteLine(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteLine", reflect.TypeOf((*MockTextOutput)(nil).WriteLine), text)
}
