// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapters/handlers/cli/command_runner.go
//
// Generated by this command:
//
//	mockgen -source=internal/adapters/handlers/cli/command_runner.go -destination=internal/adapters/handlers/cli/mocks/mock_command_runner.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	ports "idx/internal/core/ports"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockrunnableCommand is a mock of runnableCommand interface.
type MockrunnableCommand struct {
	ctrl     *gomock.Controller
	recorder *MockrunnableCommandMockRecorder
	isgomock struct{}
}

// MockrunnableCommandMockRecorder is the mock recorder for MockrunnableCommand.
type MockrunnableCommandMockRecorder struct {
	mock *MockrunnableCommand
}

// NewMockrunnableCommand creates a new mock instance.
func NewMockrunnableCommand(ctrl *gomock.Controller) *MockrunnableCommand {
	mock := &MockrunnableCommand{ctrl: ctrl}
	mock.recorder = &MockrunnableCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrunnableCommand) EXPECT() *MockrunnableCommandMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockrunnableCommand) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockrunnableCommandMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockrunnableCommand)(nil).Run))
}

// MockindexableCommand is a mock of indexableCommand interface.
type MockindexableCommand struct {
	ctrl     *gomock.Controller
	recorder *MockindexableCommandMockRecorder
	isgomock struct{}
}

// MockindexableCommandMockRecorder is the mock recorder for MockindexableCommand.
type MockindexableCommandMockRecorder struct {
	mock *MockindexableCommand
}

// NewMockindexableCommand creates a new mock instance.
func NewMockindexableCommand(ctrl *gomock.Controller) *MockindexableCommand {
	mock := &MockindexableCommand{ctrl: ctrl}
	mock.recorder = &MockindexableCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockindexableCommand) EXPECT() *MockindexableCommandMockRecorder {
	return m.recorder
}

// Inspect mocks base method.
func (m *MockindexableCommand) Inspect(indexPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", indexPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Inspect indicates an expected call of Inspect.
func (mr *MockindexableCommandMockRecorder) Inspect(indexPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockindexableCommand)(nil).Inspect), indexPath)
}

// Run mocks base method.
func (m *MockindexableCommand) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockindexableCommandMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockindexableCommand)(nil).Run))
}

// Sync mocks base method.
func (m *MockindexableCommand) Sync() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync")
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockindexableCommandMockRecorder) Sync() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockindexableCommand)(nil).Sync))
}

// Watch mocks base method.
func (m *MockindexableCommand) Watch(showUpdatedFiles bool, debounce time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", showUpdatedFiles, debounce)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockindexableCommandMockRecorder) Watch(showUpdatedFiles, debounce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockindexableCommand)(nil).Watch), showUpdatedFiles, debounce)
}

// MocksearchableCommand is a mock of searchableCommand interface.
type MocksearchableCommand struct {
	ctrl     *gomock.Controller
	recorder *MocksearchableCommandMockRecorder
	isgomock struct{}
}

// MocksearchableCommandMockRecorder is the mock recorder for MocksearchableCommand.
type MocksearchableCommandMockRecorder struct {
	mock *MocksearchableCommand
}

// NewMocksearchableCommand creates a new mock instance.
func NewMocksearchableCommand(ctrl *gomock.Controller) *MocksearchableCommand {
	mock := &MocksearchableCommand{ctrl: ctrl}
	mock.recorder = &MocksearchableCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksearchableCommand) EXPECT() *MocksearchableCommandMockRecorder {
	return m.recorder
}

// RunWithOptions mocks base method.
func (m *MocksearchableCommand) RunWithOptions(query string, options ports.SearchOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunWithOptions", query, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunWithOptions indicates an expected call of RunWithOptions.
func (mr *MocksearchableCommandMockRecorder) RunWithOptions(query, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithOptions", reflect.TypeOf((*MocksearchableCommand)(nil).RunWithOptions), query, options)
}

// MockdaemonableCommand is a mock of daemonableCommand interface.
type MockdaemonableCommand struct {
	ctrl     *gomock.Controller
	recorder *MockdaemonableCommandMockRecorder
	isgomock struct{}
}

// MockdaemonableCommandMockRecorder is the mock recorder for MockdaemonableCommand.
type MockdaemonableCommandMockRecorder struct {
	mock *MockdaemonableCommand
}

// NewMockdaemonableCommand creates a new mock instance.
func NewMockdaemonableCommand(ctrl *gomock.Controller) *MockdaemonableCommand {
	mock := &MockdaemonableCommand{ctrl: ctrl}
	mock.recorder = &MockdaemonableCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdaemonableCommand) EXPECT() *MockdaemonableCommandMockRecorder {
	return m.recorder
}

// Disable mocks base method.
func (m *MockdaemonableCommand) Disable(projectPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", projectPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockdaemonableCommandMockRecorder) Disable(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockdaemonableCommand)(nil).Disable), projectPath)
}

// Enable mocks base method.
func (m *MockdaemonableCommand) Enable(projectPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable", projectPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enable indicates an expected call of Enable.
func (mr *MockdaemonableCommandMockRecorder) Enable(projectPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockdaemonableCommand)(nil).Enable), projectPath)
}

// Status mocks base method.
func (m *MockdaemonableCommand) Status() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(error)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockdaemonableCommandMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockdaemonableCommand)(nil).Status))
}
