// Code generated by MockGen. DO NOT EDIT.
// Source: idx/internal/features/skills (interfaces: Installer)

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSkillsInstaller is a mock of Installer interface.
type MockSkillsInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockSkillsInstallerMockRecorder
	isgomock struct{}
}

// MockSkillsInstallerMockRecorder is the mock recorder for MockSkillsInstaller.
type MockSkillsInstallerMockRecorder struct {
	mock *MockSkillsInstaller
}

// NewMockSkillsInstaller creates a new mock instance.
func NewMockSkillsInstaller(ctrl *gomock.Controller) *MockSkillsInstaller {
	mock := &MockSkillsInstaller{ctrl: ctrl}
	mock.recorder = &MockSkillsInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillsInstaller) EXPECT() *MockSkillsInstallerMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockSkillsInstaller) Cleanup(tempDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", tempDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockSkillsInstallerMockRecorder) Cleanup(tempDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockSkillsInstaller)(nil).Cleanup), tempDir)
}

// CloneRepo mocks base method.
func (m *MockSkillsInstaller) CloneRepo(out io.Writer) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneRepo", out)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneRepo indicates an expected call of CloneRepo.
func (mr *MockSkillsInstallerMockRecorder) CloneRepo(out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneRepo", reflect.TypeOf((*MockSkillsInstaller)(nil).CloneRepo), out)
}

// RunInstallScript mocks base method.
func (m *MockSkillsInstaller) RunInstallScript(dir, editor string, out io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInstallScript", dir, editor, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInstallScript indicates an expected call of RunInstallScript.
func (mr *MockSkillsInstallerMockRecorder) RunInstallScript(dir, editor, out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInstallScript", reflect.TypeOf((*MockSkillsInstaller)(nil).RunInstallScript), dir, editor, out)
}
