// Code generated by MockGen. DO NOT EDIT.
// Source: idx/internal/features/skills (interfaces: Installer)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSkillsInstaller is a mock of Installer interface.
type MockSkillsInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockSkillsInstallerMockRecorder
	isgomock struct{}
}

// MockSkillsInstallerMockRecorder is the mock recorder for MockSkillsInstaller.
type MockSkillsInstallerMockRecorder struct {
	mock *MockSkillsInstaller
}

// NewMockSkillsInstaller creates a new mock instance.
func NewMockSkillsInstaller(ctrl *gomock.Controller) *MockSkillsInstaller {
	mock := &MockSkillsInstaller{ctrl: ctrl}
	mock.recorder = &MockSkillsInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillsInstaller) EXPECT() *MockSkillsInstallerMockRecorder {
	return m.recorder
}

// Install mocks base method.
func (m *MockSkillsInstaller) Install(editor, projectRoot string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", editor, projectRoot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Install indicates an expected call of Install.
func (mr *MockSkillsInstallerMockRecorder) Install(editor, projectRoot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockSkillsInstaller)(nil).Install), editor, projectRoot)
}
