name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Run cyclomatic complexity check
        run: make complexity

      - name: Run unit tests
        run: make test
